export default {
  extends: ["stylelint-config-standard-scss"],
  rules: {
    "alpha-value-notation": "number",
    "color-named": "never",
    "color-function-notation": "modern",
    "declaration-no-important": true,
    "import-notation": "string",
    "length-zero-no-unit": true,
    "number-max-precision": 3,

    "selector-max-id": 0,
    "selector-max-universal": 1,
    "selector-max-type": 2,
    "selector-max-class": 3,
    "selector-max-compound-selectors": 3,
    "selector-no-qualifying-type": true,
    "max-nesting-depth": 3,

    "selector-max-specificity": "0,3,0",
    "declaration-block-no-duplicate-properties": true,
    "no-duplicate-selectors": true,

    "value-no-vendor-prefix": true,
    "property-no-vendor-prefix": true,
    "selector-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": true,

    "at-rule-no-vendor-prefix": true,
    "function-linear-gradient-no-nonstandard-direction": true,

    "declaration-block-single-line-max-declarations": 1,
    "shorthand-property-no-redundant-values": true,
    "declaration-block-no-redundant-longhand-properties": true,

    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": true,

    "order/properties-order": [
      "position",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",
      "display",
      "flex-direction",
      "flex-wrap",
      "justify-content",
      "align-items",
      "align-content",
      "gap",
      "width",
      "height",
      "margin",
      "padding",
      "border",
      "background",
      "color",
      "font-family",
      "font-size",
      "font-weight",
      "line-height",
      "text-align",
      "transform",
      "transition",
    ],

    "selector-class-pattern": "^[a-z][a-zA-Z0-9]*$",

    "media-feature-name-no-unknown": true,
    "media-feature-range-notation": "context",

    "keyframes-name-pattern": "^[a-z][a-zA-Z0-9]*$",
    "time-min-milliseconds": 100,
  },
  plugins: ["stylelint-order", "stylelint-scss"],
};
